#!/usr/bin/env node
/**
 * Build script - Generate static assets module
 * Reads admin UI files and creates a JavaScript module with content as strings
 */

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');

// Read admin UI files
const indexHtml = readFileSync(join(rootDir, 'admin/index.html'), 'utf8');
const stylesCss = readFileSync(join(rootDir, 'admin/styles.css'), 'utf8');
const appJs = readFileSync(join(rootDir, 'admin/app.js'), 'utf8');

// Generate module content
const moduleContent = `/**
 * Static assets - Admin UI files
 * Auto-generated by scripts/build-static.js - DO NOT EDIT MANUALLY
 */

export const STATIC_ASSETS = {
  'index.html': ${JSON.stringify(indexHtml)},
  'styles.css': ${JSON.stringify(stylesCss)},
  'app.js': ${JSON.stringify(appJs)},
};
`;

// Write to worker/src/static-assets.js
const outputPath = join(rootDir, 'worker/src/static-assets.js');
writeFileSync(outputPath, moduleContent, 'utf8');

console.log('✅ Static assets generated:', outputPath);
